### ISSUE TITLE
Better to use transitionTo instead of path

### ISSUE THREAD

**Issue by Freyskeyd** [grena/project-mauna#2]
Hey,

If you base your routing on `state` it's better to use `transitionTo` to move accros page.

https://github.com/grena/project-mauna/blob/develop/public/js/app.js#L16

``` javascript
$location.path('/login');
```

To

``` javascript
$state.transitionTo('login');
```

**Comment by grena** [comment]
Oh ok, I didn't know that, thanks for tip :) Will do it in a next commit.
