### ISSUE TITLE
Guidelines improvment

### ISSUE THREAD

**Issue by Freyskeyd** [grena/project-mauna#3]
Hey,

To make a better workflow and a clean project we need to complete the guidelines:

https://github.com/grena/project-mauna/wiki/Guidelines

Some explaination on what the project is, and what it need to be can be a good part!

**Comment by grena** [comment]
I'm working on it ;) Thanks !

**Comment by Freyskeyd** [comment]
For PHP Architecture, we'll use Repositery Pattern.

## Javascript part
- [x] RequireJS
- [x] RequireJS domReady
- [x] Angular
- [x] Restangular

## Unit tests JS
- [x] Protractor 
- [x] Karma

## Js Concept
- [x] :+1: Using late Bootstrapping
- :-1: Using lazy loading
- [x] :+1: Test first
- [x] :+1: e2e JS testing
- [x] :+1: Gulp tasks

## Swag
- :+1: Using Agile concept to drive project ? (Sprint, Userstory)
